General:
    seed: 0
    log_path: logs/freeze_last_half_perceiver_2 ### TODO: change this each time training to avoid overwriting logs
    epochs: 100
    patience: 5
Data:
    data_path: '/root/project/dataset/annotations'
    clip_duration: 2  # Duration of sampled clip for each video
    num_frames: 16  # Number of frames to sample from each clip
    batch_size: 32
    num_workers: 32
    video_path_prefix: '/root/project/dataset/hmdb51'
Model:
    num_classes: 51
    perceiver:
        num_freq_bands: 32
        depth: 2 # Ablate
        max_freq: 56.
        input_axis: 3
        num_latents: 16
        latent_dim: 128
        cross_heads: 1
        latent_heads: 4
        cross_dim_head: 128 # Ablate
        latent_dim_head: 32
        num_classes: 51
        attn_dropout: 0.5
        ff_dropout: 0.5
        self_per_cross_attn: 1 # Ablate
        final_classifier_head: True
    lr: 0.0001
    weight_decay: 0.001