General:
    seed: 0
    log_path: logs/R(2+1)D_Cross_Self_Attention
    epochs: 100
    patience: 5
Data:
    data_path: '/root/project/dataset/annotations'
    clip_duration: 4  # Duration of sampled clip for each video
    num_frames: 16  # Number of frames to sample from each clip
    batch_size: 8
    num_workers: 8
    video_path_prefix: '/root/project/dataset/hmdb51'
Model:
    num_classes: 51
    cross_attention:
        num_freq_bands: 6 # Check paper
        max_freq: 10. # Check paper
        input_axis: 3 # Video has 3 axis
        num_latents: 256
        latent_dim: 512
        cross_heads: 1
        cross_dim_head: 64
        attn_dropout: 0
        ff_dropout: 0
        fourier_encode_data: True
    self_attention:
        depth: 6
        latent_dim: 512
        latent_heads: 8
        latent_dim_head: 64
        num_classes: 51
        attn_dropout: 0.
        ff_dropout: 0.
    lr: 0.0001
    weight_decay: 0.00001
    epochs: 100