General:
    seed: 0
    log_path: logs/cnn_1self_2 ### TODO: change this each time training to avoid overwriting logs
    epochs: 100
    patience: 5
Data:
    data_path: '/root/project/dataset/annotations'
    clip_duration: 2  # Duration of sampled clip for each video
    num_frames: 16  # Number of frames to sample from each clip
    batch_size: 32
    num_workers: 32
    video_path_prefix: '/root/project/dataset/hmdb51'
Model:
    num_classes: 51
    # cross_attention:
    #     num_freq_bands: 6 # Check paper
    #     max_freq: 10. # Check paper
    #     num_classes: 51
    #     input_axis: 3 # Video has 3 axis
    #     num_latents: 64
    #     latent_dim: 128
    #     cross_heads: 1
    #     cross_dim_head: 128
    #     attn_dropout: 0.5
    #     ff_dropout: 0.5
    #     fourier_encode_data: False
    self_attention:
        depth: 1
        latent_dim: 512 # No cross: set = dim from cnn
        latent_heads: 8
        latent_dim_head: 64
        num_classes: 51
        attn_dropout: 0.5
        ff_dropout: 0.5
    lr: 0.00005
    weight_decay: 0.001